[package]
name = "wt-regression"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = { version = "0.3.0", default-features = false }
wasmtime = "0.37.0"
anyhow = "1"

[[bench]]
name = "wasmtime_benchmark"
harness = false
